Converted webview elements have no resourceId package prefix and are ignored by Appium
appium/appium-android-bootstrap pull request #34
Opened 2016-10-24 22:15 UTC by ssynix

Fix for appium/appium#6608: HTML element ids don't seem to have any package id prepended to them in the page source, so when Appium tries to prepend a package name to them, it ends up not finding them.

2016-10-27 18:22 UTC, ssynix commented
@imurchie @jlipps I'd appreciate if you guys could review this!

2016-10-28 00:21 UTC, jlipps commented
@ssynix what's the rationale for finding webview elements in a native context, rather than switching to the webview context?

2016-10-28 14:22 UTC, ssynix commented
We've had a lot of trouble with webviews in the past both on Android (ChromeDriver) and iOS (ios-webkit-debug-proxy). With ChromeDriver 2.25, and both appium-remote-debugger and ios-webkit-debug-proxy from source, most of these issues seem to have been resolved (haven't tested extensively since I only have this configuration locally, not on our device lab). It's also twice the effort to make sure these extra dependencies are compatible with the device OS, or something like Android System Webview. Staying in native as much as possible allows us to avoid these potential flakiness.

The main rationale behind this PR, however, is that these elements are returned with a `resource-id` attribute in the page source, and should be queryable with `findElementById`, effectively making this a bug. At the very least, it is confusing to see an element in the source returned by Appium and not know why Appium doesn't see it.

2016-10-28 21:32 UTC, jlipps commented
fair enough, I'm +1 for including this. @imurchie?

2016-11-01 20:28 UTC, imurchie commented
Looks good to me! Thanks for this!

2016-11-01 20:28 UTC, imurchie requested changes
Can you make sure you've signed the CLA, then we can get this in and published!

2016-11-03 21:42 UTC, ssynix reviewed
Done.

2016-11-03 21:56 UTC, imurchie approved these changes

2016-11-03 21:57 UTC, merged

2016-11-03 21:59 UTC, imurchie commented
Published in `appium-android-bootstrap@2.7.7`.